version: '3.7'

services:
  postgresflow:
    build:
      context: .  # Path to the directory containing the Dockerfile
    restart: always
    image: ${POSTGRES_IMAGE_NAME}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '6432:5432'
    networks:
      - rest-dataflow-studio-network
    volumes:
      - rest-dataflow-studio-utilflow-postgresflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  rest-dataflow-studio-network:
    driver: bridge
    name: rest-dataflow-studio-network 

volumes:
  rest-dataflow-studio-utilflow-postgresflow-data:
    driver: local